#
# This is a sample docker compose file to bring up a perforce stack
#
server:
  build: server
  restart: always
  hostname: p4server
  environment:
    - "P4PORT=1666"
    - "CASE_INSENSITIVE=1"
    - "ENABLE_AUTOCHECKPOINTS=1"
    - "LDAPSERVER=${LDAPSERVER}"
    - "LDAPBINDUSER=${LDAPBINDUSER}"
    - "LDAPBINDPASSWD=${LDAPBINDPASSWD}"
    - "LDAPSEARCHBASE=${LDAPSEARCHBASE}"
  volumes:
    - "/mnt/datavolumes/perforce-server/data:/data"
    - "/mnt/datavolumes/perforce-server/library:/library"
  ports:
    - "1666:1666"
  log_opt:
    max-size: "50m"
    max-file: "5"

fusion:
  build: git-fusion
  restart: always
  hostname: p4git
  environment:
    - "P4PORT=server:1666"
    - "P4USER=p4admin"
  ports:
    - "2222:22"
  volumes:
    - "/mnt/datavolumes/git-fusion:/data"
  links:
    - server
  log_opt:
    max-size: "50m"
    max-file: "5"

proxy:
  build: proxy
  restart: always
  hostname: p4proxy
  environment:
     - "P4TARGET=server:1666"
     - "P4USER=p4admin"
     - "P4PASSWD=DhP5rYyBgz"
     - "P4CLIENT=proxy_populate_ws"
     - "CACHE_MAX_SIZE_MB=16"
     - "CACHE_MAX_EMPTY_MB=0"
     - "PARALLEL_SYNC=4"
  ports:
    - "1667:1666"
  volumes:
     - "/mnt/datavolumes/perforce-proxy:/data"
  links:
     - server
  log_opt:
    max-size: "50m"
    max-file: "5"

helix-git-connector:
  build: git-connector
  ports:
    - "443:443"
